### ISSUE TITLE
Can it inited network and connect outside ip by host network?

### ISSUE THREAD

**Issue by seewindcn** [danobi/vmtest#12]
I want to test network functions inside vm, How to do? 
Thanks

**Comment by danobi** [comment]
Hi, you should be able to use loopback interface on kernel targets as well as create network devices (provided driver support is built with =y into the kernel). On image targets whatever your image has configured should be available.

That being said, the guest is not bridged to the host, so you will probably not be able to access the internet from the guest.

**Comment by seewindcn** [comment]
get it, thanks
