### ISSUE TITLE
init.sh configurability

### ISSUE THREAD

**Issue by chantra** [danobi/vmtest#31]
I was playing with vmtest to see how this could run tests for bpf in kernel-patches/vmtest

Aside from only supporting x86_64 currently, which porting to support other arch seems doable, there is a couple of other things missing for tests to run successfully in that env.

Most of it is to do with the environment setup.

Currently, what we use is essentially captured in https://github.com/libbpf/ci/blob/main/rootfs/mkrootfs_tweak.sh

but here is how I would get bpf selftests to run and work for the most part:
```
vmtest -k $KERNEL_REPO/arch/x86_64/boot/bzImage "ip link set lo up && /bin/mount bpffs /sys/fs/bpf -t bpf && umount /sys/kernel/debug/tracing && ./test_progs
```

I don't think it is easy, nor reasonable, to have a init.sh that rule them all, but it seems that it would benefit from a bit more flexibility.

What do you think would be a good approach to make this more customizable?

**Comment by danobi** [comment]
I think supporting a custom init would be reasonable. There's already quite a few config options: https://github.com/danobi/vmtest/blob/master/docs/config.md

But looking at `mkrootfs_tweak.sh`, it seems like that could be done in a script rather than the 1-liner interface? To put it differently: are there pid 1 specific things that need to be done?

**Comment by chantra** [comment]
> I think supporting a custom init would be reasonable. There's already quite a few config options: https://github.com/danobi/vmtest/blob/master/docs/config.md
> 
> But looking at `mkrootfs_tweak.sh`, it seems like that could be done in a script rather than the 1-liner interface? 

Oh sure, those commands could be wrapped in a script that essentially run the commands I showed and then `exec "$@"`.

> To put it differently: are there pid 1 specific things that need to be done?

I don't think there is anything pid 1 specific that need to happen provided that the host gets into a state where commands can be ran and tweaked. But there is probably value in "templating" the existing init script.

**Comment by danobi** [comment]
Sure, templating is reasonable to me as well. Feel free to propose a mechanism - I've got a pretty wide latitude for accepting things at the moment. Still trying to explore the vmtest space.

**Comment by chantra** [comment]
> Sure, templating is reasonable to me as well. Feel free to propose a mechanism - I've got a pretty wide latitude for accepting things at the moment. Still trying to explore the vmtest problem space.

Thanks, I will try to think of it and cook something up when I see a pressing need :D.

**Comment by chantra** [comment]
going to close in the meantime.
