### ISSUE TITLE
Stream command output

### ISSUE THREAD

**Issue by danobi** [danobi/vmtest#39]
Currently for long running commands inside the guest, the output is completely buffered until the command exits. This is fine for short commands. But for longer running ones, it is a bad experience for the user. Cuz it looks like it's hung.

I tried to upstream some output streaming features to upstream qemu-guest-agent but upstream preferred to keep the guest-exec API simple. They suggested to use `virtio-serial` to stream data between guest and host instead: https://fedoraproject.org/wiki/Features/VirtioSerial .

`virtio-serial` seems entirely reasonable. Basically you redirect all output from command in the guest to the virtio-serial port. And vmtest on host can poll from it and provide streaming output.

**Comment by chantra** [comment]
yes agreed.... it is kind of annoying. Thanks for looking into it and creating an issue, this saved me some time not having to dig through this :).

**Comment by danobi** [comment]
Ah, good reminder. Unless you're already working on it, I can put this on my todo list this week

**Comment by chantra** [comment]
> Ah, good reminder. Unless you're already working on it, I can put this on my todo list this week

It is more of an annoyance to me ATM but something I will eventually look into, probably not this week though :)
