### ISSUE TITLE
No output/not working on Fedora 38

### ISSUE THREAD

**Issue by kuba-moo** [danobi/vmtest#41]
Hi! I'm trying to get `vmtest` to work for netdev. I managed to get `virtme-ng` to boot my custom kernel, but vmtest is not happy:

```
$ vmtest -k build_mm/vmlinux "echo Running!"
=> vmlinux
===> Booting
Failed to connect QGA

Caused by:
    Timed out waiting for QGA connection

$ qemu-kvm --version
QEMU emulator version 7.2.6 (qemu-7.2.6-1.fc38)
```

Any ideas what it can be?

**Comment by danobi** [comment]
Hi! Any interesting logs in `.vmtest.log`? Also mind trying this PR out? Maybe something interesting will pop out. https://github.com/danobi/vmtest/pull/42

**Comment by danobi** [comment]
Also may be useful to try any one of the known-good bzImages the CI uses: https://github.com/danobi/vmtest/releases/tag/test_assets

That would help narrow down guest kconfig vs host config issue.
