### ISSUE TITLE
one-liner: return command RC

### ISSUE THREAD

**Issue by chantra** [danobi/vmtest#43]
vmtest RC returns the number of failures. That is, in one-liner mode, 0 on success, 1 on failure.

When running in one-liner mode (or when running only one command), it can be useful to return the actual code of the command if possible.

I understand this would be diverging from the multi-runs RC but it make usage slightly easier.

Here is an example use-case.

I was bissecting a failing test in bpf selftest. That test was newly introduced and `test_progs` would return `2/ENOENT` if the test is non-existent, 0 on success, 1 on failure.
When integrating with `git bissect run`, from outside `vmtest`, the ENOENT would look like a failure, e.g vmtest would return 1. If the RC of the command was actually returned, it would be easier to handle the RC from outside of vmtest.

I don't have super strong opinion on this because it is always possible to either:
- `tail -n1` on stderr and grep for the last digit
- write the RC to a shared file between the vm and the host and reuse that from outside of vmtest.

But it would be more ergonomic if this was directly available from vmtest RC.

WDYT?

**Comment by danobi** [comment]
Agreed, better to return RC from vmtest cli.

Somewhat related, but I've been kinda thinking the config file is not _super_ useful. Seems like it mostly gets in the way these days.

**Comment by chantra** [comment]
> 
> Somewhat related, but I've been kinda thinking the config file is not _super_ useful. Seems like it mostly gets in the way these days.

I suppose it depends on the use case. For me, indeed, I leverage it as one-liner as it is more convenient to adjust the command-line than the config.
