### ISSUE TITLE
mounting /mnt/vmtest with 9pfs cache=mmap option

### ISSUE THREAD

**Issue by chantra** [danobi/vmtest#61]
It seems /mnt/vmtest mount is mounted with "cache=loose" option since https://github.com/danobi/vmtest/commit/ea6216191a8c82e6378a8344f3c3e72e2582d38d

One issue with cache=loose, is that the [guest does not revalidate from the host](https://lore.kernel.org/lkml/CAFkjPTmVbyuA0jEAjYhsOsg-SE99yXgehmjqUZb4_uWS_L-ZTQ@mail.gmail.com/), and based on [the 9p documentation](https://www.kernel.org/doc/Documentation/filesystems/9p.txt) it seems it should be use for RO filesystem?

https://wiki.qemu.org/Documentation/9p_root_fs#Boot_the_9p_Root_FS_System goes over this. It seems `cache=mmap` is the least required to have a functional system.

It becomes useful when paired with the interactive mode as this would allow, for instance, to iterate on bpf selftests (from the host) and quickly re-run them in the guest without the need to reboot. See https://chantra.github.io/bpfcitools/bpf-local-development.html

WDYT?

**Comment by danobi** [comment]
Agreed, looks like cache=loose is a bug now that it's not RO. 

But it's not clear to me the difference between cache=none and cache=mmap. If mmap works for you then I suppose it's fine.

**Comment by danobi** [comment]
Ah I see that in the qemu wiki now. Somewhat odd semantics... but sounds like cache=mmap is what we want
