### ISSUE TITLE
Host services (like docker )are not supported

### ISSUE THREAD

**Issue by thugrock7** [danobi/vmtest#63]
I am using vmtest to run ebpf tests and tests include some docker commands. I have docker up and running in host machine but via vmtest the commands fail. Found that /var/run/docker.sock is not able to access from vmtest command, where as that is available in host machine. Any wrap around so that I can solve this problem?

**Comment by danobi** [comment]
Hi, thanks for trying vmtest! I have an entry in the FAQ for this as well as a workaround: https://github.com/danobi/vmtest/blob/master/docs/faqs.md#how-do-i-run-docker-inside-vmtest
