### ISSUE TITLE
Make mounting of more file systems optional?

### ISSUE THREAD

**Issue by d-e-s-o** [danobi/vmtest#76]
I wanted to run a test that is located on `/tmp` in `vmtest`. To my surprise it was not found. The reason seems to be that we unconditionally mount `/tmp` ourselves, effectively shadowing anything the host would otherwise provide:

https://github.com/danobi/vmtest/blob/27dd99927b1268121a9a619b6b6d6768ef198328/src/init/init.sh#L56-L57

(Why) do we need to mount `/tmp`? It seems entirely unlikely that the host does not have it. Could/should we just check if it's present and not do anything if so? I suppose similar arguments can be made for `/run`, btw.

**Comment by danobi** [comment]
The reason it's like that is b/c the original intent was to make guest activity separated from the host, except for the shared directory. Over time that changed b/c it was a bit annoying to not be able to write to root host, esp. if the writing occurred in tools outside your control.

As a workaround, you could do this:

```
[[target]]
name = "test"
kernel = "/home/dlxu/scratch/bzImage-v6.6-empty"
command = "ls -l /tmp/hosttmp"
[target.vm.mounts]
"/tmp/hosttmp" = { host_path = "/tmp", writable = true }
```

Do you think that'd work for you or would it be better to expose host tmpfs?

**Comment by d-e-s-o** [comment]
Ah, interesting. I suppose that could be made to work, though ergonomics would be pretty bad if I had to be in a certain directory so as to have the program [source](https://github.com/danobi/vmtest?tab=readme-ov-file#config-file-interface) the config file. It would be different story if there was support for a global config, I think.

But also, conceptually, while I understand a more isolated world is where you are coming from, as you say yourself that stance changed. And at least for me one major differentiating factor of the program is that it effectively allows me to swap out the kernel while keeping everything else the same (of course there are limits). So...why the push for keeping `/tmp` isolated by default and then allowing users to shadow that mount with a host mount, versus just keeping the host mount to begin with?
