### ISSUE TITLE
QGA sync failed, retrying", EAGAIN

### ISSUE THREAD

**Issue by bjackman** [danobi/vmtest#96]
Thanks for this great tool! I've only started some initial adoption but it seems extremely useful.

I've been somewhat stress-testing it by running this script on every commit in my kernel branch, with up to 8 runs happening in parallel, whenever I commit anything:

```sh
set -ex
exec 2>&1

git clean -fdx -e .vscode # mrproper isn't always good enough

make -j defconfig
scripts/config -d HYPERV -d CONFIG_PARAVIRT -e MITIGATION_ADDRESS_SPACE_ISOLATION \
    -e CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT -e KVM -e KVM_INTEL -e KVM_AMD -e DEBUG_ENTRY
make olddefconfig
make -sj8 bzImage headers CC='ccache gcc' KBUILD_BUILD_TIMESTAMP=

make -sj8 CC='ccache gcc' -C tools/testing/selftests install TARGETS=mm

# Embed the config here so we get the benefit of local-ci's cache invalidation logic
# Per https://github.com/danobi/vmtest/blob/master/docs/config.md,
# Anyway, vmtest interprets paths relative to the location of its config file,
# instead of the actual CWD. So we need the config to be in the CWD.
# If you enable more tests in the config below you'll also need to update TARGETS above.
cat <<EOF > vmtest.toml
[[target]]
name = "x86 mm selftests"
kernel = "./arch/x86/boot/bzImage"
kernel_args = "asi=on pti=off"
# Doesn't work, dunno why:
# KSELFTEST_RUN_VMTESTS_SH_ARGS="-t mmap" /mnt/kselftest_install/run_kselftest.sh --test mm:run_vmtests.sh
# All of these have test failures and you can't disable individual tests:
# ./run_vmtests.sh -t mmap
# ./run_vmtests.sh -t gup_test
# ./run_vmtests.sh -t mlock
# Flaky:
# ./run_vmtests.sh -t mremap
# Doesn't work at all:
# ./run_vmtests.sh -t userfaultfd
# Require kernel config changes:
# ./run_vmtests.sh -t "vmalloc hmm ksm"
command = """
./run_vmtests.sh -t cow
cd /mnt/kselftest_install/mm/
"""

[target.vm.mounts]
"/mnt/kselftest_install" = { host_path = "./tools/testing/selftests/kselftest_install" }
EOF

vmtest --config vmtest.toml
```

That `CONFIG_MITIGATION_ADDRESS_SPACE_ISOLATION` is not in the upstream kernel, I think it should be irrelevant here but just in case it could be got from [this RFC](https://lore.kernel.org/linux-mm/20240712-asi-rfc-24-v1-0-144b319a40d8@google.com/). 

Anyway, sometimes I get this error:

```
[2024-11-15T17:14:22Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:14:23Z INFO  vmtest::qga] Connecting to QGA (1)
[2024-11-15T17:14:28Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:14:29Z INFO  vmtest::qga] Connecting to QGA (2)
[2024-11-15T17:14:34Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:14:35Z INFO  vmtest::qga] Connecting to QGA (3)
[   19.423322] tsc: Refined TSC clocksource calibration: 1999.840 MHz
[   19.426990] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x39a72de5fd2, max_idle_ns: 881590574448 ns
[   19.431847] clocksource: Switched to clocksource tsc
[2024-11-15T17:14:40Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:14:41Z INFO  vmtest::qga] Connecting to QGA (4)
[2024-11-15T17:14:46Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:14:47Z INFO  vmtest::qga] Connecting to QGA (5)
[2024-11-15T17:14:52Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:14:53Z INFO  vmtest::qga] Connecting to QGA (6)
[2024-11-15T17:14:59Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:15:00Z INFO  vmtest::qga] Connecting to QGA (7)
[2024-11-15T17:15:05Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:15:06Z INFO  vmtest::qga] Connecting to QGA (8)
[2024-11-15T17:15:11Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:15:12Z INFO  vmtest::qga] Connecting to QGA (9)
[2024-11-15T17:15:17Z WARN  vmtest::qga] QGA sync failed, retrying: Resource temporarily unavailable (os error 11)
[2024-11-15T17:15:18Z DEBUG vmtest::qemu] Child still alive, killing
[2024-11-15T17:15:18Z DEBUG vmtest::qemu] qemu stderr: qemu-system-x86_64: Guest says index 40947 is available
    qemu-system-x86_64: Guest says index 40947 is available
    qemu-system-x86_64: Guest says index 40947 is available
    
Failed to connect QGA

Caused by:
    Timed out waiting for QGA connection
FAILED
```

Could this be some sort of resource leak? I haven't researched how QGA works so apologies if it's something obvious

**Comment by danobi** [comment]
> Thanks for this great tool! I've only started some initial adoption but it seems extremely useful.

Glad it's useful for you!

> Could this be some sort of resource leak? I haven't researched how QGA works so apologies if it's something obvious

I haven't seen this before. I don't see much online about it, but from grepping qemu code I see 3 places where this error could be coming from. Most plausible would be:

```c
/* Called within rcu_read_lock().  */
static bool virtqueue_get_head(VirtQueue *vq, unsigned int idx,
                               unsigned int *head)
{
    /* Grab the next descriptor number they're advertising, and increment
     * the index we've seen. */
    *head = vring_avail_ring(vq, idx % vq->vring.num);

    /* If their number is silly, that's a fatal mistake. */
    if (*head >= vq->vring.num) {
        virtio_error(vq->vdev, "Guest says index %u is available", *head);
        return false;
    }

    return true;
}
```

I wonder if it's b/c host is being stressed and can't keep up with processing virtqueues? Just a wild guess. Seems like a bug on qemu side if I had to guess. Probably worth filing an issue with them.

**Comment by bjackman** [comment]
> host is being stressed and can't keep up with processing virtqueues

Oh - that reminds me! I'm running all this via `chrt --idle 0` which is pretty brutal. So if I'm doing something intensive at normal priority QEMU and vmtest will get totally starved. When I'm compiling a kernel with every driver in the world this goes on for ages. 

So... maybe this is kinda WAI? I should try a less sledgehammer approach to the scheduling prioritisation and see if the issue goes away.

**Comment by danobi** [comment]
> So... maybe this is kinda WAI?

Well judging from the tone of the comment in qemu source, it sounds like there's a bug on an obscure code path. I'd still encourage a bug report :P

**Comment by bjackman** [comment]
I raised https://gitlab.com/qemu-project/qemu/-/issues/2690

**Comment by chantra** [comment]
> Could this be some sort of resource leak? I haven't researched how QGA
> works so apologies if it's something obvious
>
> I haven't seen this before. I don't see much online about it, but from
> grepping qemu code I see 3 places where this error could be coming from.
> Most plausible would be:
>
> /* Called within rcu_read_lock().  */static bool virtqueue_get_head(VirtQueue *vq, unsigned int idx,
>                                unsigned int *head)
> {
>     /* Grab the next descriptor number they're advertising, and increment     * the index we've seen. */
>     *head = vring_avail_ring(vq, idx % vq->vring.num);
>
>     /* If their number is silly, that's a fatal mistake. */
>     if (*head >= vq->vring.num) {
>         virtio_error(vq->vdev, "Guest says index %u is available", *head);
>         return false;
>     }
>
>     return true;
> }
>
> I wonder if it's b/c host is being stressed and can't keep up with
> processing virtqueues? Just a wild guess. Seems like a bug on qemu side if
> I had to guess. Probably worth filing an issue with them.
>


FYI, I have seen similar problem even with an internal implementation of vm
testing, AFAICT it correlates with host resources being somewhat stressed.
There is probably some race condition that happen in that path which is
exacerbated with usage. That being said, no concluding investigation has
been done so far, so take my comment more as anecdotal then anything.

**Comment by bjackman** [comment]
I don't know for sure yet but just noting here in case I forget to update later... I think the `Guest says index %u is available` may actually be caused by a guest kernel bug in my case.

I discovered a (currentlyt unknown) bug in my kernel where it silently fails to boot on some platforms. When I reproduce that in QEMU, it prints the  `Guest says index %u is available`. When I boot a kernel without my bug I don't see that message.

**Comment by bjackman** [comment]
Had a nice debugging odyssey on Friday night. This has been my own kernel bug all along. I should have guessed, but it's just very rare for these patches to break stuff so subtly as this, so I jumped to the conclusion that it was a tooling issue! My patches broke a little-used allocator path so that virtio's pages weren't being allocated. This led to a garbage virting index being written out to the device. When the QEMU code says `If their number is silly, that's a fatal mistake` , "they" means the guest virtio driver. Sorry for the noise on this!
